import {
  FrequencySpectrumChart,
  HarmonicsChart,
  SpectrogramChart,
  VocalWeightChart,
  VolumeChart,
} from "@/components/voice-analytics";
import { RAINBOW_PASSAGE_LINES, RAINBOW_PASSAGE_TITLE } from "@/data/readingPassages";
import type { VoiceAnalyticsTool } from "@/features/exercises/toolTypes";


export const voiceAnalyticsTools: VoiceAnalyticsTool[] = [
  {
    id: "vocal-weight",
    name: "Vocal Weight",
    description: "Track voice weight stability while recording.",
    shortInstruction: "Use a comfortable sustained sound and keep intensity steady while monitoring weight changes.",
    readingPassageTitle: RAINBOW_PASSAGE_TITLE,
    readingPassageLines: RAINBOW_PASSAGE_LINES,
    visualAid: "general",
    showReset: true,
    requiresPitchGraph: false,
    requiresResonanceGraph: false,
    requiresGenderGraph: false,
    Component: VocalWeightChart,
  },
  {
    id: "volume",
    name: "Volume Monitor",
    description: "Visualize loudness consistency through the take.",
    shortInstruction: "Read one short phrase repeatedly and keep loudness even from start to finish.",
    readingPassageTitle: RAINBOW_PASSAGE_TITLE,
    readingPassageLines: RAINBOW_PASSAGE_LINES,
    visualAid: "breathing",
    showReset: true,
    requiresPitchGraph: false,
    requiresResonanceGraph: false,
    requiresGenderGraph: false,
    Component: VolumeChart,
  },
  {
    id: "harmonics",
    name: "Harmonics",
    description: "Inspect harmonic balance alongside live recording.",
    shortInstruction: "Sustain an easy vowel and compare harmonic shape while keeping a relaxed tone.",
    readingPassageTitle: RAINBOW_PASSAGE_TITLE,
    readingPassageLines: RAINBOW_PASSAGE_LINES,
    visualAid: "resonance",
    showReset: true,
    requiresPitchGraph: false,
    requiresResonanceGraph: true,
    requiresGenderGraph: false,
    Component: HarmonicsChart,
  },
  {
    id: "spectrum",
    name: "Frequency Spectrum",
    description: "View distribution of voice energy by frequency bands.",
    shortInstruction: "Speak naturally for a few seconds and observe where most voice energy sits in the spectrum.",
    readingPassageTitle: RAINBOW_PASSAGE_TITLE,
    readingPassageLines: RAINBOW_PASSAGE_LINES,
    visualAid: "pitch",
    showReset: true,
    requiresPitchGraph: true,
    requiresResonanceGraph: false,
    requiresGenderGraph: false,
    Component: FrequencySpectrumChart,
  },
  {
    id: "spectrogram",
    name: "Spectrogram",
    description: "See spectral intensity over time in one view.",
    shortInstruction: "Hold a steady sound, then vary tone slightly and watch how the spectrogram pattern shifts.",
    readingPassageTitle: RAINBOW_PASSAGE_TITLE,
    readingPassageLines: RAINBOW_PASSAGE_LINES,
    visualAid: "humming",
    showReset: true,
    requiresPitchGraph: true,
    requiresResonanceGraph: true,
    requiresGenderGraph: false,
    Component: SpectrogramChart,
  },
];
